In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./gps_log.csv", encoding = "utf-8")

In [3]:
df

                        rtime provider device_name   latitude  longtitude
0     2020-10-23 03:09:09.382      gps     device0  37.384141  126.854119
1     2020-10-23 03:09:09.382      gps     device0  37.384141  126.854119
2     2020-10-23 03:09:10.382      gps     device0  37.384256  126.854570
3     2020-10-23 03:09:10.382      gps     device0  37.384256  126.854570
4     2020-10-23 03:09:11.382      gps     device0  37.384319  126.854734
...                       ...      ...         ...        ...         ...
3861  2020-10-23 03:47:06.000      gps     device0  37.391097  126.971910
3862  2020-10-23 03:47:07.000      gps     device0  37.391121  126.971917
3863  2020-10-23 03:47:07.000      gps     device0  37.391121  126.971917
3864  2020-10-23 03:47:08.000      gps     device0  37.391222  126.971951
3865  2020-10-23 03:47:08.000      gps     device0  37.391222  126.971951

[3866 rows x 5 columns]

In [4]:
df.isnull().sum()

rtime          0
provider       0
device_name    0
latitude       0
longtitude     0
dtype: int64

In [5]:
df.duplicated().sum()

1933

In [6]:
log_df = df.drop_duplicates()
log_df

                        rtime provider device_name   latitude  longtitude
0     2020-10-23 03:09:09.382      gps     device0  37.384141  126.854119
2     2020-10-23 03:09:10.382      gps     device0  37.384256  126.854570
4     2020-10-23 03:09:11.382      gps     device0  37.384319  126.854734
6     2020-10-23 03:09:12.382      gps     device0  37.384319  126.854734
8     2020-10-23 03:09:13.000      gps     device0  37.384319  126.854734
...                       ...      ...         ...        ...         ...
3856  2020-10-23 03:47:04.000      gps     device0  37.391064  126.971899
3858  2020-10-23 03:47:05.000      gps     device0  37.391075  126.971903
3860  2020-10-23 03:47:06.000      gps     device0  37.391097  126.971910
3862  2020-10-23 03:47:07.000      gps     device0  37.391121  126.971917
3864  2020-10-23 03:47:08.000      gps     device0  37.391222  126.971951

[1933 rows x 5 columns]

In [7]:
log_df.duplicated().sum()

0

In [8]:
log_df = log_df.reset_index()
log_df

,index,rtime,provider,device_name,latitude,longtitude
0,0,2020-10-23 03:09:09.382,gps,device0,37.384141,126.854119
1,2,2020-10-23 03:09:10.382,gps,device0,37.384256,126.854570
2,4,2020-10-23 03:09:11.382,gps,device0,37.384319,126.854734
3,6,2020-10-23 03:09:12.382,gps,device0,37.384319,126.854734
4,8,2020-10-23 03:09:13.000,gps,device0,37.384319,126.854734
...,...,...,...,...,...,...
1928,3856,2020-10-23 03:47:04.000,gps,device0,37.391064,126.971899
1929,3858,2020-10-23 03:47:05.000,gps,device0,37.391075,126.971903
1930,3860,2020-10-23 03:47:06.000,gps,device0,37.391097,126.971910
1931,3862,2020-10-23 03:47:07.000,gps,device0,37.391121,126.971917
1932,3864,2020-10-23 03:47:08.000,gps,device0,37.391222,126.971951

In [9]:
log_df = log_df.drop('index', axis = 1)
log_df

                        rtime provider device_name   latitude  longtitude
0     2020-10-23 03:09:09.382      gps     device0  37.384141  126.854119
1     2020-10-23 03:09:10.382      gps     device0  37.384256  126.854570
2     2020-10-23 03:09:11.382      gps     device0  37.384319  126.854734
3     2020-10-23 03:09:12.382      gps     device0  37.384319  126.854734
4     2020-10-23 03:09:13.000      gps     device0  37.384319  126.854734
...                       ...      ...         ...        ...         ...
1928  2020-10-23 03:47:04.000      gps     device0  37.391064  126.971899
1929  2020-10-23 03:47:05.000      gps     device0  37.391075  126.971903
1930  2020-10-23 03:47:06.000      gps     device0  37.391097  126.971910
1931  2020-10-23 03:47:07.000      gps     device0  37.391121  126.971917
1932  2020-10-23 03:47:08.000      gps     device0  37.391222  126.971951

[1933 rows x 5 columns]

In [13]:
# log_df['rtime'] = log_df['rtime'].str.slice(start=0, stop = 19)
# log_df

log_df['date'] = log_df['rtime'].str.slice(start=0, stop = 10)
log_df['time'] = log_df['rtime'].str.slice(start=11, stop = 19)

log_df

,rtime,provider,device_name,latitude,longtitude,date,time
0,2020-10-23 03:09:09,gps,device0,37.384141,126.854119,2020-10-23,03:09:09
1,2020-10-23 03:09:10,gps,device0,37.384256,126.854570,2020-10-23,03:09:10
2,2020-10-23 03:09:11,gps,device0,37.384319,126.854734,2020-10-23,03:09:11
3,2020-10-23 03:09:12,gps,device0,37.384319,126.854734,2020-10-23,03:09:12
4,2020-10-23 03:09:13,gps,device0,37.384319,126.854734,2020-10-23,03:09:13
...,...,...,...,...,...,...,...
1928,2020-10-23 03:47:04,gps,device0,37.391064,126.971899,2020-10-23,03:47:04
1929,2020-10-23 03:47:05,gps,device0,37.391075,126.971903,2020-10-23,03:47:05
1930,2020-10-23 03:47:06,gps,device0,37.391097,126.971910,2020-10-23,03:47:06
1931,2020-10-23 03:47:07,gps,device0,37.391121,126.971917,2020-10-23,03:47:07
1932,2020-10-23 03:47:08,gps,device0,37.391222,126.971951,2020-10-23,03:47:08

In [14]:
log_df = log_df[['date', 'time', 'provider', 'device_name', 'latitude', 'longtitude']]
log_df

            date      time provider device_name   latitude  longtitude
0     2020-10-23  03:09:09      gps     device0  37.384141  126.854119
1     2020-10-23  03:09:10      gps     device0  37.384256  126.854570
2     2020-10-23  03:09:11      gps     device0  37.384319  126.854734
3     2020-10-23  03:09:12      gps     device0  37.384319  126.854734
4     2020-10-23  03:09:13      gps     device0  37.384319  126.854734
...          ...       ...      ...         ...        ...         ...
1928  2020-10-23  03:47:04      gps     device0  37.391064  126.971899
1929  2020-10-23  03:47:05      gps     device0  37.391075  126.971903
1930  2020-10-23  03:47:06      gps     device0  37.391097  126.971910
1931  2020-10-23  03:47:07      gps     device0  37.391121  126.971917
1932  2020-10-23  03:47:08      gps     device0  37.391222  126.971951

[1933 rows x 6 columns]

In [16]:
# log_df.to_csv("./1023_gps_log.csv", index=False)