In [1]:
import pandas as pd
import numpy as np

In [18]:
gps_0 = pd.read_csv('./device0_gps_2020-11-07_edit.csv', encoding = 'utf-8')
gps_0

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:14:16,gps,device0,37.391009,126.973803,-35.134254,52.069386,192,1604722456094
1,2020-11-07 13:14:17,gps,device0,37.390537,126.973369,88.033963,53.731890,96,1604722457158
2,2020-11-07 13:14:18,gps,device0,37.390071,126.973497,89.759763,47.150444,48,1604722458158
3,2020-11-07 13:14:25,gps,device0,37.388576,126.972667,111.154548,27.398783,32,1604722465258
4,2020-11-07 13:14:26,gps,device0,37.388506,126.972497,132.388571,0.000000,24,1604722466999
...,...,...,...,...,...,...,...,...,...
7706,2020-11-07 16:22:10,gps,device0,37.359742,126.966695,105.883528,0.000000,24,1604733730000
7707,2020-11-07 16:22:11,gps,device0,37.359746,126.966708,105.867140,0.000000,24,1604733731000
7708,2020-11-07 16:22:12,gps,device0,37.359749,126.966718,105.868950,0.000000,16,1604733732000
7709,2020-11-07 16:22:14,gps,device0,37.359763,126.966749,105.946112,0.000000,16,1604733734000
7710,2020-11-07 16:22:15,gps,device0,37.359763,126.966752,105.952015,0.000000,16,1604733735000

In [35]:
gps_1 = pd.read_csv('./device1_gps_2020-11-07_edit.csv', encoding = 'utf-8')
gps_1

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:14:39,gps,device1,37.389346,126.972683,-96.465741,2.189828,128,1604722479930
1,2020-11-07 13:14:40,gps,device1,37.389157,126.972628,-77.795322,1.539148,128,1604722480930
2,2020-11-07 13:14:41,gps,device1,37.388702,126.972642,-23.420517,0.000000,96,1604722481930
3,2020-11-07 13:14:42,gps,device1,37.389036,126.972675,-38.413860,0.000000,64,1604722482930
4,2020-11-07 13:14:43,gps,device1,37.389068,126.972657,-37.758244,0.000000,48,1604722483930
...,...,...,...,...,...,...,...,...,...
4918,2020-11-07 16:17:36,gps,device1,37.336048,126.980682,65.434135,81.289490,32,1604733456999
4919,2020-11-07 16:17:37,gps,device1,37.336266,126.980623,72.180573,81.974686,32,1604733457999
4920,2020-11-07 16:17:38,gps,device1,37.336452,126.980602,78.130398,81.967090,24,1604733458999
4921,2020-11-07 16:17:39,gps,device1,37.336637,126.980555,82.778617,82.902540,24,1604733459999
4922,2020-11-07 16:17:40,gps,device1,37.336842,126.980459,86.804960,84.419820,24,1604733460999

In [20]:
gps_2 = pd.read_csv('./device2_gps_2020-11-07_edit.csv', encoding = 'utf-8')
gps_2

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:15:02,gps,device2,37.389417,126.972288,-23.589586,0.650529,128,1604722502138
1,2020-11-07 13:15:03,gps,device2,37.389562,126.972305,-31.997837,1.528352,128,1604722503138
2,2020-11-07 13:15:04,gps,device2,37.389723,126.972549,-91.891854,0.000000,128,1604722504138
3,2020-11-07 13:15:05,gps,device2,37.389349,126.972734,44.299328,0.000000,96,1604722505138
4,2020-11-07 13:15:06,gps,device2,37.389116,126.972778,44.710784,0.000000,64,1604722506138
...,...,...,...,...,...,...,...,...,...
5033,2020-11-07 16:15:51,gps,device2,37.318557,126.992018,124.044648,68.383410,24,1604733351000
5034,2020-11-07 16:15:52,gps,device2,37.318640,126.991819,124.938303,0.000000,24,1604733352000
5035,2020-11-07 16:15:53,gps,device2,37.318716,126.991639,124.877317,0.000000,32,1604733353000
5036,2020-11-07 16:15:54,gps,device2,37.318811,126.991465,124.227385,0.000000,32,1604733354000
5037,2020-11-07 16:22:08,gps,device2,37.359607,126.967010,55.559344,0.000000,48,1604733728000

In [37]:
gps_data_concat = pd.concat([gps_0, gps_1, gps_2])
gps_data_concat = gps_data.reset_index()

In [43]:
gps_data_concat = gps_data_concat[['rtime', 'provider', 'device_name', 'latitude', 'longtitude', 'altitude', 'speed', 'accuracy', 'time_utc']]
gps_data_concat

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:14:16,gps,device0,37.391009,126.973803,-35.134254,52.069386,192,1604722456094
1,2020-11-07 13:14:17,gps,device0,37.390537,126.973369,88.033963,53.731890,96,1604722457158
2,2020-11-07 13:14:18,gps,device0,37.390071,126.973497,89.759763,47.150444,48,1604722458158
3,2020-11-07 13:14:25,gps,device0,37.388576,126.972667,111.154548,27.398783,32,1604722465258
4,2020-11-07 13:14:26,gps,device0,37.388506,126.972497,132.388571,0.000000,24,1604722466999
...,...,...,...,...,...,...,...,...,...
17667,2020-11-07 16:15:51,gps,device2,37.318557,126.992018,124.044648,68.383410,24,1604733351000
17668,2020-11-07 16:15:52,gps,device2,37.318640,126.991819,124.938303,0.000000,24,1604733352000
17669,2020-11-07 16:15:53,gps,device2,37.318716,126.991639,124.877317,0.000000,32,1604733353000
17670,2020-11-07 16:15:54,gps,device2,37.318811,126.991465,124.227385,0.000000,32,1604733354000
17671,2020-11-07 16:22:08,gps,device2,37.359607,126.967010,55.559344,0.000000,48,1604733728000

In [25]:
gps_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17672 entries, 0 to 17671
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rtime        17672 non-null  object
 1   provider     17672 non-null  object
 2   device_name  17672 non-null  object
 3   latitude     17672 non-null  float64
 4   longtitude   17672 non-null  float64
 5   altitude     17672 non-null  float64
 6   speed        17672 non-null  float64
 7   accuracy     17672 non-null  int64
 8   time_utc     17672 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 1.2+ MB

In [44]:
gps_data_concat.to_csv('./1107_gps_concat.csv', index=False, encoding = 'utf-8')

In [45]:
gps_data_concat_time = pd.read_csv('./1107_gps_concat_time.csv', encoding = 'utf-8')
gps_data_concat_time

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:14:16,gps,device0,37.391009,126.973803,-35.134254,52.069386,192,1.604720e+12
1,2020-11-07 13:14:17,gps,device0,37.390537,126.973369,88.033963,53.731890,96,1.604720e+12
2,2020-11-07 13:14:18,gps,device0,37.390071,126.973497,89.759763,47.150444,48,1.604720e+12
3,2020-11-07 13:14:25,gps,device0,37.388576,126.972667,111.154548,27.398783,32,1.604720e+12
4,2020-11-07 13:14:26,gps,device0,37.388506,126.972497,132.388571,0.000000,24,1.604720e+12
...,...,...,...,...,...,...,...,...,...
17667,2020-11-07 16:22:10,gps,device0,37.359742,126.966695,105.883528,0.000000,24,1.604730e+12
17668,2020-11-07 16:22:11,gps,device0,37.359746,126.966708,105.867140,0.000000,24,1.604730e+12
17669,2020-11-07 16:22:12,gps,device0,37.359749,126.966718,105.868950,0.000000,16,1.604730e+12
17670,2020-11-07 16:22:14,gps,device0,37.359763,126.966749,105.946112,0.000000,16,1.604730e+12
17671,2020-11-07 16:22:15,gps,device0,37.359763,126.966752,105.952015,0.000000,16,1.604730e+12

In [46]:
gps_data_concat_time.duplicated(['rtime']).sum()

9369

In [47]:
gps_data_concat_time.duplicated(['rtime'], keep='first')

0        False
1        False
2        False
3        False
4        False
         ...
17667    False
17668    False
17669    False
17670    False
17671    False
Length: 17672, dtype: bool

In [48]:
gps_clean_data = gps_data_concat_time.drop_duplicates('rtime', keep='first')
gps_clean_data

,rtime,provider,device_name,latitude,longtitude,altitude,speed,accuracy,time_utc
0,2020-11-07 13:14:16,gps,device0,37.391009,126.973803,-35.134254,52.069386,192,1.604720e+12
1,2020-11-07 13:14:17,gps,device0,37.390537,126.973369,88.033963,53.731890,96,1.604720e+12
2,2020-11-07 13:14:18,gps,device0,37.390071,126.973497,89.759763,47.150444,48,1.604720e+12
3,2020-11-07 13:14:25,gps,device0,37.388576,126.972667,111.154548,27.398783,32,1.604720e+12
4,2020-11-07 13:14:26,gps,device0,37.388506,126.972497,132.388571,0.000000,24,1.604720e+12
...,...,...,...,...,...,...,...,...,...
17667,2020-11-07 16:22:10,gps,device0,37.359742,126.966695,105.883528,0.000000,24,1.604730e+12
17668,2020-11-07 16:22:11,gps,device0,37.359746,126.966708,105.867140,0.000000,24,1.604730e+12
17669,2020-11-07 16:22:12,gps,device0,37.359749,126.966718,105.868950,0.000000,16,1.604730e+12
17670,2020-11-07 16:22:14,gps,device0,37.359763,126.966749,105.946112,0.000000,16,1.604730e+12
17671,2020-11-07 16:22:15,gps,device0,37.359763,126.966752,105.952015,0.000000,16,1.604730e+12

In [49]:
gps_clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8303 entries, 0 to 17671
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rtime        8303 non-null   object
 1   provider     8303 non-null   object
 2   device_name  8303 non-null   object
 3   latitude     8303 non-null   float64
 4   longtitude   8303 non-null   float64
 5   altitude     8303 non-null   float64
 6   speed        8303 non-null   float64
 7   accuracy     8303 non-null   int64
 8   time_utc     8303 non-null   float64
dtypes: float64(5), int64(1), object(3)
memory usage: 648.7+ KB

In [51]:
gps_clean_data.to_csv('./1107_merged_gps_data.csv', index = False, encoding = 'utf-8')